project_2/Login_app/urls.py
from django.urls import re_path as url
from django.urls import path
from Login_app import views

# to show images
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns



app_name = 'Login_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_page, name='login'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
]


# show images, images stored in file location and saved as urls
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

project_2/project_2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Login_app.urls')),
]

project_2/Login_app/models.py
from django.db import models
#import the built in user model
from django.contrib.auth.models import User


# we'll use username, password and email


# if we want to add extra info to user, we'll have define a new class
class UserInfo(models.Model):
    # means user er ekta field,  UserInfo er elta field er sathe connect thakbe
    # one to one relation
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    facebook_id = models.URLField(blank = True)

    # pic upload hbe 'profile_pics' directory te
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank = True)

    def __str__(self):
        return self.user.username

project_2/Login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from Login_app.models import UserInfo

class UserForm(forms.ModelForm):
    # password box e "..." dekhabe actual password na dekhaya
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta():
        model = User
        #built in model and form
        fields = ('username','email','password')


class UserInfoForm(forms.ModelForm):
    class Meta():
        model = UserInfo
        fields = ('facebook_id','profile_pic')

project_2/Login_app/views.py
from django.shortcuts import render
from Login_app.forms import UserForm, UserInfoForm
from Login_app.models import UserInfo
from django.contrib.auth.models import User

# for html login page

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.

def index(request):

    dict = {}
    # views.py er fn er vitor jodi check kora lage j login kora kina
    if request.user.is_authenticated:
        current_user = request.user # fetch logged_in users info in current_user

        print(current_user.username) 
        print(current_user.email)
        print(current_user.id) # primary key of that user in database
        # prints in console after refresh the page in browser:
        # rafid
        # wap.alnahiyan425@gmail.com
        # 1

        user_id = current_user.id
        user_basic_info = User.objects.get(pk=user_id)
        user_more_info = UserInfo.objects.get(user__pk=user_id)
        # NOTE: in UserInfo.objects.get(user__pk=user_id)
        # Structure: "relationship_Variable"+ "__" + "j table er sathe relationship kora hoise tar column"
        # here in model.py, in UserInfo fn, "user" is used to make one-to-one relationship
        # in relashipships, evabe use kora hy
        # "user" holo "UserInfo" er column
        # "pk" holo "User" er column
        # "__" diye separate kora hoy column 2ta
        # "user_id" match korbe "pk" er sathe
       

        dict = {
            "user_basic_info": user_basic_info,
            "user_more_info": user_more_info,
        }

    return render(request, 'Login_app/index.html', dict)


def register(request):

    registered = False

    # form submit korle
    if request.method == 'POST':
        user_form = UserForm(data = request.POST)
        user_info_form = UserInfoForm(data = request.POST)

        if user_form.is_valid() and user_info_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)  # encrypt password 
            user.save()  # update password with encrypted password


            user_info = user_info_form.save(commit=False) # false rakhle direct db te jabe na, hold kore rakhbe. it's used to collect the informaton in user_info variable
            user_info.user = user  
            #user table and user_info table er entry relate korbe
            # mane user_info class er "user filed" "user" object er sathe connct kore
            # "user" object e ase "user_form" er information
            # "user_info" object e ase "user_info_form" er information


            #check files
            # profile picture upload korse kina
            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic'] # request.FILES['profile_pic'] eta diye file k 'profile_pic' folder e upload kore
            
            user_info.save()
            registered = True

    
    # initially submit korar age
    else:
        user_form = UserForm()
        user_info_form = UserInfoForm()

    dict = {'user_form': user_form, 'user_info_form': user_info_form, 'registered':registered }
    return render(request, 'Login_app/register.html', context= dict)




def login_page(request):
    return render(request, 'Login_app/login.html', context= {})


# er form direct html diye ashbe
def user_login(request):
    if request.method == 'POST':

        # ekhane get('username') er 'username' holo login.html er <input name="username"/>
        username = request.POST.get('username')
        password = request.POST.get('password')

        # authenticate username and password with database
        user = authenticate(username=username, password=password)

        if user:
            # id active kina
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('Login_app:index'))
            
                # NOTE 1.: ekhane HttpResponseRedirect use kora hoise cz, etay "view"(page content) + "url pattern"(browser er url box) change kore
                # return render(request, 'Login_app/index.html', context= {}) or return index(request) ei 2ta "just view" change kore, urlpattern ager tai thake 
                # means, se jabe index.html file ei, bt url e dekhabe login.html

                # NOTE 2. reverse() function urls.py er urlpatterns=[] er "name" dhore call korar shubidha dey
                # mane index.html dhore call na kore 'Login_app:index' dhore call korte pari
            else:
                return HttpResponse("Account is not active!")
            
        else:
            return HttpResponse("Invalid username or password!")

    # jodi form submit na hoy
    else:
        return HttpResponseRedirect(reverse('Login_app:login'))
    


# log out korar jnno user logged in thakte hbe must
# decorators to check if user logged_in or not
# used to control views for loggedin or logged_out users
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('Login_app:index'))

project_2/templates/Login_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">


    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>


    <!-- popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js" integrity="sha512-TPh2Oxlg1zp+kz3nFA0C5vVC6leG/6mm1z9+mA81MI5eaUVqasPLO8Cuk4gMF4gUfP5etR73rgU/8PNMsSesoQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>


    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <title>{{ title }}</title>
</head>


<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
            <li class="nav-item active" >
                <a class="nav-link" href="{% url 'Login_app:index' %}">Home</a>
            </li>

            <!-- checks logged_in or not , thakle nicher code show korbe-->
            {% if user.is_authenticated %}
                <li>
                    <a class="nav-link" href="{% url 'Login_app:logout' %}">Logout</a>
                </li>
            
            {% else %}
                <li>
                    <a class="nav-link" href="{% url 'Login_app:register' %}">Register</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'Login_app:login' %}">Login</a>
                </li>
            {% endif %}

        </ul>
    </nav>

    <div class="container" style="padding-top:20px">

        {% block body_block %}

        {% endblock %}

    </div>
</body>
</html>

project_2/templates/Login_app/index.html
{% extends "Login_app/base.html" %}
{% block body_block %}


{% if user.is_authenticated %}
    <p>Hi {{ user_basic_info.username}}</p>
    <p>Your E-mail: {{ user_basic_info.email}}</p>
    <p><a href="{{ user_more_info.facebook_id }}">Facebook Profile</a></p> 

    <!-- img show hoy: /folder location/{file url from database} -->
    <img src = "/media/{{ user_more_info.profile_pic }}" width="200px">

{% else %}
    <div class="alert alert-primary">You are not logged in!</div>

{% endif %}


{% endblock %}

project_2/templates/Login_app/login.html
{% extends 'Login_app/base.html' %}
{% block body_block %}

<h3>Please Login</h3>

<!-- 1. html diye data pass korte "action=" use korte hy, ekhane j file e pass korte chai tar "urls.py" er "urlpatterns" er "name" dite hbe "app_name:" er pore
      2. urls.py er maddhome oi data views.py e jabe-->
<form action="{% url 'Login_app:user_login' %}" method="post">

    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username..." required class="form-control">
    <label for="password">Password:</label>
    <input type="password" name="password" placeholder="Enter Password..." required class="form-control">
    {% csrf_token %}
    <br>
    <input type="submit" name="submit" value="Login">
</form>


{% endblock %}

project_2/templates/Login_app/register.html
{% extends 'Login_app/base.html' %}
{% load static %}
{% block body_block %}

{% if registered %}
    <div class="alert alert-success">Congratulations! Registration Successful</div>

{% else %}

    <!--form upload er jnno use korle enctype ="multipart/form-data use korte hy" -->
    <form enctype="multipart/form-data" method="post">
        {{ user_form.as_p }}
        {{ user_info_form.as_p }}
        {% csrf_token %}
        <input type="submit" name="submit" value="Register">
    </form>

{% endif %}

{% endblock %}